# Generated by Django 4.2.3 on 2023-09-24 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 24, 16, 55, 46, 524350))),
                ('fullname', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mynotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 24, 16, 55, 46, 523318))),
                ('query', models.CharField(max_length=100)),
                ('opt', models.CharField(max_length=100)),
                ('myfiles', models.FileField(upload_to='Files')),
                ('comments', models.TextField()),
            ],
        ),
    ]
